const Country = require('../models/countrySchema')
const State = require('../models/stateSchema')
const City = require('../models/citySchema')
const Department = require('../models/departmentSchema')
const Event = require('../models/eventSchema')
const Course = require('../models/courseSchema')
const User = require('../models/userSchema')
const EventImages = require('../models/eventImagesSchema')
const UserCourse = require('../models/userCourses')

Country.hasOne(State)
State.hasOne(City)
//EventImages.hasOne(Event)
// UserCourse.belongsTo(User,{ onDelete: 'cascade' })
// UserCourse.belongsTo(Course,{ onDelete: 'cascade' })
User.belongsToMany(Course,{through:UserCourse})
Course.belongsToMany(User,{through:UserCourse})
Country.hasOne(User)
User.belongsTo(Country)
State.hasOne(User)
User.belongsTo(State)
City.hasOne(User)
User.belongsTo(City)
Department.hasOne(User)
User.belongsTo(Department)

